backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# These lines should *not* be indented
publish_mode: editorial_workflow
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - label: "Manage NUAC Information"
    name: "global"
    files:
      - label: "Common Water Messages"
        name: "site messages"
        file: "_data/site-msg.yml"
        fields:
          - { label: "Common Message Indicator", name: "msg-ind", widget: "boolean" }
          - { label: "Message Box Type", name: "box-type", widget: "select", options: ["danger", "warning", "info"] }
          - label: "Common Messages"
            name: "messages"
            widget: "list"
            fields:
              - {label: "Message Type", name: "msg-type", widget: "select", options: ["danger", "warning", "info"]}
              - {label: "Message Description", name: "msg-desc", widget: "markdown", hint: "Enter message to show on each Waters page"}
      - label: "Specific Messages Per Water"
        name: "water messages"
        file: "_data/water-msg.yml"
          - { label: "Grove Open", name: "grove-msg-ind", widget: "boolean" }
          - { label: "Grove Message Indicator", name: "grove-msg-ind", widget: "boolean" }
          - { label: "Grove Msg Box Type", name: "grove-box-type", widget: "select", options: ["danger", "warning", "info"] }
          - label: "Grove Messages"
            name: "grove-messages"
            widget: "list"
            fields:
              - {label: "Message Type", name: "msg-type", widget: "select", options: ["danger", "warning", "info"]}
              - {label: "Message Description", name: "msg-desc", widget: "markdown", hint: "Enter message to show on a given Waters page"}
          - { label: "BIF Open", name: "bif-msg-ind", widget: "boolean" }
          - { label: "BIF Message Indicator", name: "bif-msg-ind", widget: "boolean" }
          - { label: "BIF Msg Box Type", name: "bif-box-type", widget: "select", options: ["danger", "warning", "info"] }
          - label: "BIF Messages"
            name: "bif-messages"
            widget: "list"
            fields:
              - {label: "Message Type", name: "msg-type", widget: "select", options: ["danger", "warning", "info"]}
              - {label: "Message Description", name: "msg-desc", widget: "markdown", hint: "Enter message to show on a given Waters page"}
          - { label: "Yare Open", name: "yare-msg-ind", widget: "boolean" }
          - { label: "Yare Message Indicator", name: "yare-msg-ind", widget: "boolean" }
          - { label: "Yare Msg Box Type", name: "yare-box-type", widget: "select", options: ["danger", "warning", "info"] }
          - label: "Yare Messages"
            name: "Yare-messages"
            widget: "list"
            fields:
              - {label: "Message Type", name: "msg-type", widget: "select", options: ["danger", "warning", "info"]}
              - {label: "Message Description", name: "msg-desc", widget: "markdown", hint: "Enter message to show on a given Waters page"}
          - { label: "Snetterton Open", name: "snp-msg-ind", widget: "boolean" }
          - { label: "Snetterton Message Indicator", name: "snp-msg-ind", widget: "boolean" }
          - { label: "Snetterton Msg Box Type", name: "snp-box-type", widget: "select", options: ["danger", "warning", "info"] }
          - label: "Snetterton Messages"
            name: "snp-messages"
            widget: "list"
            fields:
              - {label: "Message Type", name: "msg-type", widget: "select", options: ["danger", "warning", "info"]}
              - {label: "Message Description", name: "msg-desc", widget: "markdown", hint: "Enter message to show on a given Waters page"}
          - { label: "Trinity Broads Open", name: "fib-msg-ind", widget: "boolean" }
          - { label: "Trinity Broads Message Indicator", name: "fib-msg-ind", widget: "boolean" }
          - { label: "Trinity Broads Msg Box Type", name: "fib-box-type", widget: "select", options: ["danger", "warning", "info"] }
          - label: "Trinity Broads Messages"
            name: "fib-messages"
            widget: "list"
            fields:
              - {label: "Message Type", name: "msg-type", widget: "select", options: ["danger", "warning", "info"]}
              - {label: "Message Description", name: "msg-desc", widget: "markdown", hint: "Enter message to show on a given Waters page"}
          - { label: "Hall Walk Open", name: "hw-msg-ind", widget: "boolean" }
          - { label: "Hall Walk Message Indicator", name: "hw-msg-ind", widget: "boolean" }
          - { label: "Hall Walk Msg Box Type", name: "hw-box-type", widget: "select", options: ["danger", "warning", "info"] }
          - label: "Hall Walk Messages"
            name: "hw-messages"
            widget: "list"
            fields:
              - {label: "Message Type", name: "msg-type", widget: "select", options: ["danger", "warning", "info"]}
              - {label: "Message Description", name: "msg-desc", widget: "markdown", hint: "Enter message to show on a given Waters page"}
          - { label: "NDAA Open", name: "ndaa-msg-ind", widget: "boolean" }
          - { label: "NDAA Message Indicator", name: "ndaa-msg-ind", widget: "boolean" }
          - { label: NDAAF Msg Box Type", name: "ndaa-box-type", widget: "select", options: ["danger", "warning", "info"] }
          - label: "NDAA Messages"
            name: "ndaa-messages"
            widget: "list"
            fields:
              - {label: "Message Type", name: "msg-type", widget: "select", options: ["danger", "warning", "info"]}
              - {label: "Message Description", name: "msg-desc", widget: "markdown", hint: "Enter message to show on a given Waters page"}
          - { label: "Hickling Broad Open", name: "hib-msg-ind", widget: "boolean" }
          - { label: "Hickling Broad Message Indicator", name: "hib-msg-ind", widget: "boolean" }
          - { label: "Hickling Broad Msg Box Type", name: "hib-box-type", widget: "select", options: ["danger", "warning", "info"] }
          - label: "Hickling Broad Messages"
            name: "hib-messages"
            widget: "list"
            fields:
              - {label: "Message Type", name: "msg-type", widget: "select", options: ["danger", "warning", "info"]}
              - {label: "Message Description", name: "msg-desc", widget: "markdown", hint: "Enter message to show on a given Waters page"}

# collections:
#   - label: "Manage NDAA Information"
#     name: "global"
#     files:
#       - label: "Cover Page"
#         name: "cover"
#         file: "_data/cover.yml"
#         fields:
#           - { label: "Cover Message Indicator", name: "cover-msg-ind", widget: "boolean" }
#           - label: "Cover Messages"
#             name: "cover-messages"
#             widget: "list"
#             fields:
#               - {label: "Cover Message Type", name: "msg-type", widget: "select", options: ["warning", "info"]}
#               - {label: "Cover Message Description", name: "cvr-msg", widget: "markdown", hint: "Add message detail"}
#       - label: "Membership Info"
#         name: "membership"
#         file: "_data/membership.yml"
#         fields:
#           - { label: "Introduction", name: "intro-desc", widget: "markdown" }
#           - { label: "Fee Message Indicator", name: "alert-msg-ind", widget: "boolean" }
#           - label: "Fee Message"
#             name: "alert-messages"
#             widget: "list"
#             fields:
#               - {label: "Fee Message Type", name: "alert-type", widget: "select", options: ["warning", "info"]}
#               - {label: "Fee Message Description", name: "alert-msg", widget: "markdown", hint: "Indicate latest Fee changes"}
#           - label: "Fee Options"
#             name: "options"
#             widget: "list"
#             fields:
#               - {label: "Fee Option Description", name: "option-desc", widget: "markdown", hint: "Blank row = <p>&nbsp</p>"}              
#       - label: "Stockists"
#         name: "stockists"
#         file: "_data/stockists.yml"
#         fields:
#           - label: "Stockists"
#             name: "stockists"
#             widget: "list"
#             fields:
#               - {label: "Name", name: "name", widget: "string", hint: "PW Angling"}
#               - {label: "Address Line 1", name: "addr-1", widget: "string", hint: "57 Long John Hill"}
#               - {label: "Address Line 2", name: "addr-2", widget: "string", default: "null", hint: "Norwich"}
#               - {label: "Address Line 3", name: "addr-3", widget: "string", default: "null", required: false}
#               - {label: "Address Line 4", name: "addr-4", widget: "string", default: "null", required: false}
#               - {label: "Post Code", name: "postcode", widget: "string", pattern: ["[A-IK-PR-UWYZ]?[A-H,K-Y][0-9]?[0-9A-HJKMNP-Y][ ][0-9][ABD-HJLNP-UW-Z][ABD-HJLNP-UW-Z]", "Must be a valid UK Postcode"], hint: "NRnn nAX"}
#               - {label: "Logo", name: "logo", widget: "hidden", default: "null"}
#               - {label: "URL Type", name: "url-type", widget: "select", options: ["web", "fb"], hint: "select website or facebook"}
#               - {label: "URL Reference", name: "url", widget: "string", hint: "Enter website or facebook https:// address"}